version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "23:00"
    open-pull-requests-limit: 10
    reviewers:
    - mdgreenwald
    labels:
    - "python"
    - "dependencies"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "23:00"
    open-pull-requests-limit: 10
    reviewers:
    - mdgreenwald
    labels:
    - "docker"
    - "dependencies"

