---
apiVersion: v1
kind: Namespace
metadata:
  name: swish
  labels:
    name: swish

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swish
  namespace: swish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swish
  template:
    metadata:
      labels:
        app: swish
    spec:
      containers:
      - name: swish
        image: swish:latest
        command: ["poetry", "run", "python", "src/main.py"]
        ports:
        - containerPort: 8080
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5

---