name: "security-scan"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        docker build -t swish:latest .

  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  scan:
    runs-on: ubuntu-latest
    steps:
      -
        name: Docker Scout
        uses: docker/scout-action@v1.10.0
        command: quickview
        image: swish:latest
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
